title: hadassahharland
email: hadassah.harland@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hadassah Harland
# baseurl: "/"
url: "https://hadassahharland.github.io" # the base hostname & protocol for your site, e.g. http://example.com
